### ISSUE TITLE
Terminate cabal-core & swarm on _destroy

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-client#12]
Are the cabal-core and the swarm also being terminated? Otherwise it'll continue peering and indexing.

(If this is non-trivial, we can make an issue & a future PR!)

_Originally posted by @noffle in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mjc2Mjg4OTYz/pull_request_reviews/more_threads_

**Comment by cblgh** [comment]
places it needs to be fixed (sorry for the screenshots, couldn't really link it handily from the pr while maintaining context)

![image](https://user-images.githubusercontent.com/3862362/64078589-de8a7c80-ccdc-11e9-8cfb-069db2ca9e80.png)

![image](https://user-images.githubusercontent.com/3862362/64078598-ee09c580-ccdc-11e9-9d12-c38ca9de47fd.png)

![image](https://user-images.githubusercontent.com/3862362/64078601-fc57e180-ccdc-11e9-90d2-0cfcb2264143.png)

**Comment by cblgh** [comment]
probably works

**Comment by nikolaiwarner** [comment]
@cblgh in Desktop, when a cabal was removed from the client and then added back in the same session, it'd crash because the db or swarm or something are still open.

Desktop calls client.removeCabal here: https://github.com/cabal-club/cabal-desktop/blob/ada966773b422b8acfb2242885fd08a8869cfac6/app/actions.js#L89

**Comment by cblgh** [comment]
o dang

**Comment by noffle** [comment]
We fixed this!
