### ISSUE TITLE
Allow mods to archive channels

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-client#68]
I think it makes sense to bundle channel archiving within the current mods/admins system. It could be used to clean-up channel listings from accidentally made channels, or to hide vulgarly named channels.

Question: **where does this functionality make the most sense—in cabal-client or cabal-core?**

Example commands:
```
/archive <channel>
/unarchive <channel> (alt. /restore <channel>)
/archives (lists all archived channels, the archiver (good idea?), and the stated reason for archiving)
```

older issue on this topic: https://github.com/cabal-club/cabal-client/issues/16

**Comment by noffle** [comment]
I think it needs to be implemented in core, since the archive action will need to be a hypercore entry that gets indexed. This could be exposed via a simple api on client though, maybe even just by removing it from the channel list (no frontend work needed for this fix! other than triggering a re-render event of the channel listing).
